In [1]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /Users/msawant/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True


1. we join [A] original hasoc dataset including annotations for all tasks (Task1, Task2, Task3) with [B] relabelled dataset <br>

2. Relabelled is only done for original Task1 (HOF, NOT) <br>

3. The tweets were assigned new relabeling by matching tweet IDs from the original dataset with the relabeled dataset [Iteration1] and storing the results in a new column, New_label.<br/>

4. The New_label column stores relabeled annotations from iteration 1. For tweets that were not relabeled in this iteration, the values from Original_label are copied into New_label. <br/>

5. New column "Mismatch" assigned the value of 1 if the annotations between columns [Orginal Label] from Task1 and [New_label] from Iteration1 was different

In [2]:
import pandas as pd
import numpy as np

Original Dataset

In [3]:
file_path="dataset/Hindi_Hasoc2019.tsv"
train_df = pd.read_csv(file_path, sep="\t", encoding="utf-8")
train_df= train_df.dropna(how='all')

In [4]:
train_df.head(20)

,text_id,text,task_1,task_2,task_3
0,hasoc_hi_5556,"बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...",NOT,NONE,NONE
1,hasoc_hi_5648,सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...,HOF,PRFN,UNT
2,hasoc_hi_164,तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...,HOF,PRFN,TIN
3,hasoc_hi_3530,"बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...",NOT,NONE,NONE
4,hasoc_hi_5206,चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...,NOT,NONE,NONE
5,hasoc_hi_5121,मुंबई में बारिश से लोगों को काफी समस्या हो रही है,NOT,NONE,NONE
6,hasoc_hi_7142,Ahmed's dad:-- beta aaj teri mammy kyu nahi ba...,NOT,NONE,NONE
7,hasoc_hi_4321,"5 लाख मुसलमान उर्स में, अजमेर की दरगाह पर आते ...",NOT,NONE,NONE
8,hasoc_hi_4674,"Do mahashaktiyan mili hain, charo taraf khusi ...",NOT,NONE,NONE
9,hasoc_hi_1637,Chants of 'Jai Sri Ram' as Owaisi takes oath: ...,NOT,NONE,NONE
10,hasoc_hi_5771,नृत्य होगा..! संगीत होगा..! जीवन मे उत्सव हो...,NOT,NONE,NONE
11,hasoc_hi_288,गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...,NOT,NONE,NONE
12,hasoc_hi_1803,डॉ. मुखर्जी ने एक देश में दो विधान दो प्रधान औ...,NOT,NONE,NONE
13,hasoc_hi_5900,धार्मिक पदों पर बैठे कुछ लोग अपने को भगवान समझ...,NOT,NONE,NONE
14,hasoc_hi_5951,सिक्का मोहब्बत का उछाल रक्खा है ~ हाँ मगर खुद...,NOT,NONE,NONE
15,hasoc_hi_1723,कोन कहता है आँखो में प्यार नही होता। जो डूब...,NOT,NONE,NONE
16,hasoc_hi_1691,"वैसे शपथ के अंत में ' जय भारत,जय संविधान' बोलन...",NOT,NONE,NONE
17,hasoc_hi_2070,"एक लंबे अंतराल के बाद आपके बीच #MannKiBaat, जन...",NOT,NONE,NONE
18,hasoc_hi_6865,"#नीच'समानार्थी शब्द #मोदी' दिला तर चालेल की, ल...",HOF,OFFN,TIN
19,hasoc_hi_918,डॉक्टर की लिखी 7 दिन की दवा के बजाय 3 दिन की...,NOT,NONE,NONE

In [5]:
train_df = train_df.rename(columns={'text': 'tweet','task_1': 'Original_label' })

In [6]:
train_df.head(30)

,text_id,tweet,Original_label,task_2,task_3
0,hasoc_hi_5556,"बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...",NOT,NONE,NONE
1,hasoc_hi_5648,सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...,HOF,PRFN,UNT
2,hasoc_hi_164,तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...,HOF,PRFN,TIN
3,hasoc_hi_3530,"बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...",NOT,NONE,NONE
4,hasoc_hi_5206,चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...,NOT,NONE,NONE
5,hasoc_hi_5121,मुंबई में बारिश से लोगों को काफी समस्या हो रही है,NOT,NONE,NONE
6,hasoc_hi_7142,Ahmed's dad:-- beta aaj teri mammy kyu nahi ba...,NOT,NONE,NONE
7,hasoc_hi_4321,"5 लाख मुसलमान उर्स में, अजमेर की दरगाह पर आते ...",NOT,NONE,NONE
8,hasoc_hi_4674,"Do mahashaktiyan mili hain, charo taraf khusi ...",NOT,NONE,NONE
9,hasoc_hi_1637,Chants of 'Jai Sri Ram' as Owaisi takes oath: ...,NOT,NONE,NONE
10,hasoc_hi_5771,नृत्य होगा..! संगीत होगा..! जीवन मे उत्सव हो...,NOT,NONE,NONE
11,hasoc_hi_288,गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...,NOT,NONE,NONE
12,hasoc_hi_1803,डॉ. मुखर्जी ने एक देश में दो विधान दो प्रधान औ...,NOT,NONE,NONE
13,hasoc_hi_5900,धार्मिक पदों पर बैठे कुछ लोग अपने को भगवान समझ...,NOT,NONE,NONE
14,hasoc_hi_5951,सिक्का मोहब्बत का उछाल रक्खा है ~ हाँ मगर खुद...,NOT,NONE,NONE
15,hasoc_hi_1723,कोन कहता है आँखो में प्यार नही होता। जो डूब...,NOT,NONE,NONE
16,hasoc_hi_1691,"वैसे शपथ के अंत में ' जय भारत,जय संविधान' बोलन...",NOT,NONE,NONE
17,hasoc_hi_2070,"एक लंबे अंतराल के बाद आपके बीच #MannKiBaat, जन...",NOT,NONE,NONE
18,hasoc_hi_6865,"#नीच'समानार्थी शब्द #मोदी' दिला तर चालेल की, ल...",HOF,OFFN,TIN
19,hasoc_hi_918,डॉक्टर की लिखी 7 दिन की दवा के बजाय 3 दिन की...,NOT,NONE,NONE
20,hasoc_hi_3763,इस मादरचोद को धुण्डके गांड मे गोली मरो @Uppolice,HOF,PRFN,UNT
21,hasoc_hi_3228,"भारतीय रेल का सोमवार से बदल जाएगा टाइम-टेबल, ई...",NOT,NONE,NONE
22,hasoc_hi_5898,You cry in front of ur god Of being deceived ...,HOF,PRFN,UNT
23,hasoc_hi_3192,बस एक सवाल का जवाब चाहिए कि जिस चिटफंड घोटाले ...,NOT,NONE,NONE
24,hasoc_hi_4057,नतीजे आने से पहले ज़िम्मेदारी मिलनी शुरू हो गय...,NOT,NONE,NONE
25,hasoc_hi_6455,क्लिक करें और पढ़ें इस स्मार्टफोन के बारे में..,NOT,NONE,NONE
26,hasoc_hi_1944,हद तो तब हो जाती हैं जब आरक्षण का लाभ लेने वा...,HOF,HATE,TIN
27,hasoc_hi_1796,#AIMIM National Spokesperson @syedasimwaqar li...,NOT,NONE,NONE
28,hasoc_hi_308,हरि ॐ नमो नारायणा भजन सुनकर झूम उठा भक्तों का ...,NOT,NONE,NONE
29,hasoc_hi_4604,प्लीज कॉल मेरी जबरदस्ती चुदाई करो ना,HOF,PRFN,UNT

In [7]:
train_df["Original_label"].value_counts()

Original_label
HOF    2469
NOT    2196
Name: count, dtype: int64

New Dataset

In [ ]:
conda update openpyxl

In [9]:
#incorrect_data=pd.read_excel("dataset/InCorrect_Labels2.xlsx")
incorrect_data=pd.read_excel("dataset/Relabelled_Tweets.xlsx")
incorrect_data=incorrect_data[['Tweet ID','Tweet','Label Change']]
incorrect_data.tail(30)

     Tweet ID                                              Tweet Label Change
301      1167  बीजेपी नेता कैलाश विजयवर्गीय पत्रकार से कहता ह...          NOT
302      1166  राम....जीवन है, राम.....करुणा है,राम.....मर्या...          NOT
303      1163  #नीच कहने पर मणिशंकर को निष्कासित कर दिया गया ...          NOT
304      1140  मीडिया इतना डरी हुई और लाचार क्यो नजर आ रही है...          NOT
305      1139  वंदेमातरम पर राजनीति करने वाले अगर बिना देखे '...          NOT
306      1037  जो लोग गौडसे की पूजा करते हैं वो बाबा रामरहिम ...          NOT
307      1020  3 दिन से फंसे 2 साल के मासूम को अभी तक नही बचा...          NOT
308       878  Vadnde matram ko gane me kitnw time lgta hai y...          NOT
309       876  अगर आपको ये देखना है कि अपनी “फ़ील्ड” का “नाका...          NOT
310       872  #प्रज्ञा_ठाकुर ने #गोडसे_ज़िंदाबाद कहा तो नारा...          NOT
311       871  जेल में बंद बाबारामरहिम का बीजेपी की हरियाणा स...          NOT
312       814  क्या आपने कभी भारत के मुस्लिमो को पाकिस्तान का...          HOF
313       660  बालाकोट में “रात” को कितने “मोबाइल” चल रहे थे,...          NOT
314       633  बाई कडून पैसा घेणाऱ्याला शुद्ध मराठीत भडवा म्ह...          HOF
315       597  एक ही शब्द बना है इनके लिए #नीच, सोच से भी और ...          HOF
316       594  शर्म करो डॉक्टरो एक थप्पड़ खाई और    हड़ताल पर...          HOF
317       540  चाट ते रहो  चाट ते रहो  चाट ते रहो चाट ते रहोच...          HOF
318       474  हनीप्रीत बिना पापा #RamRahim को खेतो में रोटी ...          NOT
319       472  #AIMIM Chief @asadowaisi  says to the Chair, '...          NOT
320       471  PMModi ने 25 जून को संसद में कहा कि #WaterCris...          NOT
321       407  किसी राष्ट्र के प्रधानमंत्री के लिए अपशब्दों ग...          NOT
322       273  अपने विष्लेसण की पुड़िया बना लो और इसको अपने *...          HOF
323       123  एसे #नीच और #घटिया लोगो को #चौराहे पर   सबके स...          NOT
324       103  बुर्का भी केवल लाचार मुस्लिम औरतों के लिए है। ...          HOF
325       101  मुस्लिम लोगों से वोट मांगने वाली पार्टियां क्य...          HOF
326        13  गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...          HOF
327      3784  भारताला नाही तर संपूर्ण देशाला अहिंसेचा मार्ग ...          NOT
328      2086  एका माणसाने दुसऱ्याला #नीच म्हटले तर त्यात चुक...          HOF
329      2679  अबु आझमी तर भड़वा आहे पण हे माझा वाले पन निर्ल...          HOF
330      3735  मोदी जी का मक़सद है जहां चुनाव हो या होने वाला...          NOT

In [10]:
print("Total Length of Relabelled Tweets and Total length of unique relabelled tweets")
unique_relabelled_tweets=len(incorrect_data), incorrect_data["Tweet ID"].nunique()
print(unique_relabelled_tweets)

Total Length of Relabelled Tweets and Total length of unique relabelled tweets
(331, 325)

In [11]:
dups = incorrect_data[incorrect_data["Tweet ID"].duplicated(keep=False)].sort_values("Tweet ID")
print("length of duplicate relabelled tweets are",len(dups))
print("Duplicate Tweets are as follows")
dups

length of duplicate relabelled tweets are 12
Duplicate Tweets are as follows

     Tweet ID                                              Tweet Label Change
2        2496  कितना easy सवाल भारत क्या पूरे विश्व को पता है...          HOF
251      2496  कितना easy सवाल भारत क्या पूरे विश्व को पता है...          HOF
6        2642  लीजिये मुजराबाजी शुरू हलाला वालीयों का चोर रंड...          HOF
244      2642  लीजिये मुजराबाजी शुरू हलाला वालीयों का  चोर रं...          HOF
239      2679  अबु आझमी तर भड़वा आहे पण हे माझा वाले पन निर्ल...          HOF
329      2679  अबु आझमी तर भड़वा आहे पण हे माझा वाले पन निर्ल...          HOF
7        3808  देशभक्त मोहम्मद शमी ने तीसरे मैच में भी 5 लिया...          HOF
130      3808  देशभक्त मोहम्मद शमी ने तीसरे मैच में भी 5 लिया...          HOF
106      3992  .@ArvindKejriwal केजरीवाल सरकार की तर्ज पर झार...          NOT
134      3992  मोदी जी का मक़सद है जहां चुनाव हो या होने वाला...          NOT
54       4375  ये एक ऐसा #नीच आदमी है कि जो धवन के अंगूठे में...          NOT
56       4375  गरीब व पिछड़े लोग हर साल पैदल यात्राओं में जा ...          NOT

In [12]:
#incorrect_data['Tweet ID'] = incorrect_data['Tweet ID'].astype(int)

#incorrect_data.loc[:, "Tweet ID"] = incorrect_data["Tweet ID"].apply(lambda x: x-2)
#ids_to_check = incorrect_data["Tweet ID"].values.tolist()
#print(ids_to_check)

Creating dictionary from the relabelled dataset

In [13]:
label_map = dict(zip(incorrect_data["Tweet ID"], incorrect_data["Label Change"]))

In [14]:
print("Length of the relabelled tweets info stored in dictionary",len(label_map))
print("Values of the relabelled tweets info stored in dictonary are",label_map)

Length of the relabelled tweets info stored in dictionary 325
Values of the relabelled tweets info stored in dictonary are {3505: 'HOF', 4193: 'HOF', 2496: 'HOF', 1064: 'HOF', 2701: 'HOF', 2558: 'HOF', 2642: 'HOF', 3808: 'HOF', 4655: 'NOT', 4649: 'NOT', 4646: 'NOT', 4645: 'HOF', 4643: 'NOT', 4627: 'NOT', 4622: 'NOT', 4618: 'NOT', 4613: 'NOT', 4612: 'NOT', 4609: 'NOT', 4608: 'NOT', 4602: 'NOT', 4598: 'NOT', 4590: 'NOT', 4588: 'NOT', 4579: 'NOT', 4577: 'NOT', 4576: 'NOT', 4573: 'NOT', 4567: 'NOT', 4566: 'NOT', 4560: 'NOT', 4546: 'NOT', 4544: 'NOT', 4538: 'NOT', 4534: 'NOT', 4533: 'NOT', 4532: 'NOT', 4529: 'NOT', 4528: 'NOT', 4522: 'NOT', 4515: 'NOT', 4511: 'NOT', 4501: 'NOT', 4496: 'NOT', 4487: 'NOT', 4475: 'NOT', 4472: 'NOT', 4464: 'NOT', 4457: 'NOT', 4446: 'NOT', 4433: 'NOT', 4425: 'NOT', 4405: 'NOT', 4403: 'NOT', 4375: 'NOT', 4369: 'HOF', 4325: 'NOT', 4343: 'NOT', 4330: 'NOT', 4328: 'NOT', 4322: 'NOT', 4317: 'NOT', 4310: 'NOT', 4305: 'NOT', 4303: 'NOT', 4294: 'NOT', 4288: 'NOT', 4285: 'NOT', 4281: 'NOT', 4271: 'NOT', 4269: 'NOT', 4264: 'NOT', 4233: 'NOT', 4227: 'NOT', 4223: 'NOT', 4218: 'NOT', 4217: 'NOT', 4215: 'NOT', 4212: 'NOT', 4197: 'NOT', 4195: 'NOT', 4181: 'NOT', 4179: 'NOT', 4169: 'NOT', 4131: 'NOT', 4127: 'NOT', 4125: 'NOT', 4113: 'NOT', 4105: 'NOT', 4102: 'NOT', 4084: 'NOT', 4083: 'NOT', 4066: 'NOT', 4063: 'NOT', 4056: 'NOT', 4032: 'NOT', 4050: 'NOT', 4043: 'NOT', 4039: 'NOT', 4025: 'NOT', 4021: 'NOT', 4014: 'NOT', 4013: 'NOT', 4007: 'NOT', 3995: 'NOT', 3992: 'NOT', 3991: 'NOT', 3984: 'NOT', 3980: 'NOT', 3967: 'NOT', 3964: 'NOT', 3962: 'NOT', 3958: 'NOT', 3954: 'NOT', 3953: 'NOT', 3949: 'NOT', 3940: 'NOT', 3932: 'NOT', 3926: 'NOT', 3916: 'NOT', 3912: 'NOT', 3892: 'NOT', 3890: 'NOT', 3877: 'NOT', 3868: 'NOT', 3853: 'NOT', 3845: 'NOT', 3841: 'NOT', 3831: 'NOT', 3790: 'HOF', 3766: 'NOT', 3740: 'NOT', 3731: 'NOT', 3723: 'NOT', 3704: 'NOT', 3667: 'NOT', 3658: 'HOF', 3628: 'NOT', 3621: 'NOT', 3618: 'HOF', 3617: 'NOT', 3609: 'HOF', 3604: 'NOT', 3591: 'NOT', 3571: 'NOT', 3569: 'NOT', 3556: 'NOT', 3552: 'NOT', 3548: 'NOT', 3537: 'NOT', 3521: 'NOT', 3495: 'NOT', 3462: 'HOF', 3437: 'HOF', 3412: 'HOF', 3408: 'NOT', 3404: 'NOT', 3403: 'NOT', 3391: 'NOT', 3389: 'NOT', 3386: 'NOT', 3377: 'NOT', 3376: 'NOT', 3374: 'NOT', 3373: 'NOT', 3372: 'NOT', 3369: 'NOT', 3367: 'NOT', 3366: 'NOT', 3359: 'NOT', 3358: 'NOT', 3354: 'NOT', 3352: 'NOT', 3341: 'HOF', 3331: 'NOT', 3279: 'HOF', 3274: 'NOT', 3229: 'HOF', 3227: 'HOF', 3220: 'NOT', 3216: 'NOT', 3212: 'NOT', 3210: 'NOT', 3209: 'NOT', 3200: 'NOT', 3189: 'NOT', 3159: 'NOT', 3143: 'NOT', 3133: 'NOT', 3121: 'NOT', 3116: 'NOT', 3104: 'NOT', 3090: 'NOT', 3085: 'NOT', 3084: 'NOT', 3079: 'NOT', 3073: 'NOT', 3069: 'NOT', 3067: 'NOT', 3058: 'NOT', 3054: 'NOT', 3043: 'NOT', 3041: 'NOT', 3025: 'NOT', 3023: 'NOT', 3022: 'NOT', 3012: 'NOT', 3008: 'NOT', 3005: 'NOT', 2991: 'NOT', 2971: 'NOT', 2970: 'NOT', 2931: 'NOT', 2845: 'NOT', 2840: 'NOT', 2836: 'NOT', 2832: 'NOT', 2829: 'NOT', 2828: 'NOT', 2826: 'NOT', 2816: 'HOF', 2812: 'NOT', 2796: 'HOF', 2780: 'NOT', 2764: 'HOF', 2756: 'NOT', 2754: 'NOT', 2753: 'NOT', 2743: 'NOT', 2742: 'NOT', 2732: 'NOT', 2728: 'NOT', 2723: 'NOT', 2708: 'NOT', 2707: 'NOT', 2704: 'NOT', 2679: 'HOF', 2678: 'HOF', 2675: 'HOF', 2662: 'HOF', 2647: 'HOF', 2635: 'HOF', 2601: 'HOF', 2586: 'HOF', 2571: 'HOF', 2565: 'HOF', 2529: 'NOT', 2492: 'NOT', 2489: 'HOF', 2481: 'HOF', 2452: 'NOT', 2420: 'HOF', 2385: 'HOF', 2352: 'HOF', 2344: 'HOF', 2332: 'NOT', 2319: 'NOT', 2311: 'NOT', 2287: 'NOT', 2277: 'NOT', 2259: 'NOT', 2258: 'NOT', 2257: 'NOT', 2240: 'NOT', 2178: 'NOT', 2154: 'NOT', 2144: 'NOT', 2134: 'NOT', 2121: 'NOT', 2107: 'NOT', 2101: 'NOT', 2092: 'NOT', 2088: 'NOT', 2083: 'NOT', 2069: 'NOT', 2010: 'NOT', 1992: 'NOT', 1951: 'NOT', 1939: 'NOT', 1938: 'NOT', 1937: 'NOT', 1921: 'NOT', 1918: 'NOT', 1871: 'NOT', 1851: 'HOF', 1839: 'HOF', 1802: 'NOT', 1583: 'HOF', 1565: 'NOT', 1513: 'HOF', 1451: 'NOT', 1444: 'NOT', 1210: 'NOT', 1189: 'NOT', 1184: 'NOT', 1179: 'NOT', 1167: 'NOT', 1166: 'NOT', 1163: 'NOT', 1140: 'NOT', 1139: 'NOT', 1037: 'NOT', 1020: 'NOT', 878: 'NOT', 876: 'NOT', 872: 'NOT', 871: 'NOT', 814: 'HOF', 660: 'NOT', 633: 'HOF', 597: 'HOF', 594: 'HOF', 540: 'HOF', 474: 'NOT', 472: 'NOT', 471: 'NOT', 407: 'NOT', 273: 'HOF', 123: 'NOT', 103: 'HOF', 101: 'HOF', 13: 'HOF', 3784: 'NOT', 2086: 'HOF', 3735: 'NOT'}

Sorting the values in dictionary

In [15]:
label_map_sorted = dict(sorted(label_map.items()))
print("IDs of the relabeled tweets stored in the dictionary in ascending order \n",list(label_map_sorted.keys()))

IDs of the relabeled tweets stored in the dictionary in ascending order
 [13, 101, 103, 123, 273, 407, 471, 472, 474, 540, 594, 597, 633, 660, 814, 871, 872, 876, 878, 1020, 1037, 1064, 1139, 1140, 1163, 1166, 1167, 1179, 1184, 1189, 1210, 1444, 1451, 1513, 1565, 1583, 1802, 1839, 1851, 1871, 1918, 1921, 1937, 1938, 1939, 1951, 1992, 2010, 2069, 2083, 2086, 2088, 2092, 2101, 2107, 2121, 2134, 2144, 2154, 2178, 2240, 2257, 2258, 2259, 2277, 2287, 2311, 2319, 2332, 2344, 2352, 2385, 2420, 2452, 2481, 2489, 2492, 2496, 2529, 2558, 2565, 2571, 2586, 2601, 2635, 2642, 2647, 2662, 2675, 2678, 2679, 2701, 2704, 2707, 2708, 2723, 2728, 2732, 2742, 2743, 2753, 2754, 2756, 2764, 2780, 2796, 2812, 2816, 2826, 2828, 2829, 2832, 2836, 2840, 2845, 2931, 2970, 2971, 2991, 3005, 3008, 3012, 3022, 3023, 3025, 3041, 3043, 3054, 3058, 3067, 3069, 3073, 3079, 3084, 3085, 3090, 3104, 3116, 3121, 3133, 3143, 3159, 3189, 3200, 3209, 3210, 3212, 3216, 3220, 3227, 3229, 3274, 3279, 3331, 3341, 3352, 3354, 3358, 3359, 3366, 3367, 3369, 3372, 3373, 3374, 3376, 3377, 3386, 3389, 3391, 3403, 3404, 3408, 3412, 3437, 3462, 3495, 3505, 3521, 3537, 3548, 3552, 3556, 3569, 3571, 3591, 3604, 3609, 3617, 3618, 3621, 3628, 3658, 3667, 3704, 3723, 3731, 3735, 3740, 3766, 3784, 3790, 3808, 3831, 3841, 3845, 3853, 3868, 3877, 3890, 3892, 3912, 3916, 3926, 3932, 3940, 3949, 3953, 3954, 3958, 3962, 3964, 3967, 3980, 3984, 3991, 3992, 3995, 4007, 4013, 4014, 4021, 4025, 4032, 4039, 4043, 4050, 4056, 4063, 4066, 4083, 4084, 4102, 4105, 4113, 4125, 4127, 4131, 4169, 4179, 4181, 4193, 4195, 4197, 4212, 4215, 4217, 4218, 4223, 4227, 4233, 4264, 4269, 4271, 4281, 4285, 4288, 4294, 4303, 4305, 4310, 4317, 4322, 4325, 4328, 4330, 4343, 4369, 4375, 4403, 4405, 4425, 4433, 4446, 4457, 4464, 4472, 4475, 4487, 4496, 4501, 4511, 4515, 4522, 4528, 4529, 4532, 4533, 4534, 4538, 4544, 4546, 4560, 4566, 4567, 4573, 4576, 4577, 4579, 4588, 4590, 4598, 4602, 4608, 4609, 4612, 4613, 4618, 4622, 4627, 4643, 4645, 4646, 4649, 4655]

Assigning the new label to the train dataset

In [16]:
train_df["New_label"] = train_df.index.map(lambda idx: label_map.get(idx + 2, None))

In [17]:
train_df.head(30)

,text_id,tweet,Original_label,task_2,task_3,New_label
0,hasoc_hi_5556,"बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...",NOT,NONE,NONE,None
1,hasoc_hi_5648,सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...,HOF,PRFN,UNT,None
2,hasoc_hi_164,तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...,HOF,PRFN,TIN,None
3,hasoc_hi_3530,"बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...",NOT,NONE,NONE,None
4,hasoc_hi_5206,चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...,NOT,NONE,NONE,None
5,hasoc_hi_5121,मुंबई में बारिश से लोगों को काफी समस्या हो रही है,NOT,NONE,NONE,None
6,hasoc_hi_7142,Ahmed's dad:-- beta aaj teri mammy kyu nahi ba...,NOT,NONE,NONE,None
7,hasoc_hi_4321,"5 लाख मुसलमान उर्स में, अजमेर की दरगाह पर आते ...",NOT,NONE,NONE,None
8,hasoc_hi_4674,"Do mahashaktiyan mili hain, charo taraf khusi ...",NOT,NONE,NONE,None
9,hasoc_hi_1637,Chants of 'Jai Sri Ram' as Owaisi takes oath: ...,NOT,NONE,NONE,None
10,hasoc_hi_5771,नृत्य होगा..! संगीत होगा..! जीवन मे उत्सव हो...,NOT,NONE,NONE,None
11,hasoc_hi_288,गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...,NOT,NONE,NONE,HOF
12,hasoc_hi_1803,डॉ. मुखर्जी ने एक देश में दो विधान दो प्रधान औ...,NOT,NONE,NONE,None
13,hasoc_hi_5900,धार्मिक पदों पर बैठे कुछ लोग अपने को भगवान समझ...,NOT,NONE,NONE,None
14,hasoc_hi_5951,सिक्का मोहब्बत का उछाल रक्खा है ~ हाँ मगर खुद...,NOT,NONE,NONE,None
15,hasoc_hi_1723,कोन कहता है आँखो में प्यार नही होता। जो डूब...,NOT,NONE,NONE,None
16,hasoc_hi_1691,"वैसे शपथ के अंत में ' जय भारत,जय संविधान' बोलन...",NOT,NONE,NONE,None
17,hasoc_hi_2070,"एक लंबे अंतराल के बाद आपके बीच #MannKiBaat, जन...",NOT,NONE,NONE,None
18,hasoc_hi_6865,"#नीच'समानार्थी शब्द #मोदी' दिला तर चालेल की, ल...",HOF,OFFN,TIN,None
19,hasoc_hi_918,डॉक्टर की लिखी 7 दिन की दवा के बजाय 3 दिन की...,NOT,NONE,NONE,None
20,hasoc_hi_3763,इस मादरचोद को धुण्डके गांड मे गोली मरो @Uppolice,HOF,PRFN,UNT,None
21,hasoc_hi_3228,"भारतीय रेल का सोमवार से बदल जाएगा टाइम-टेबल, ई...",NOT,NONE,NONE,None
22,hasoc_hi_5898,You cry in front of ur god Of being deceived ...,HOF,PRFN,UNT,None
23,hasoc_hi_3192,बस एक सवाल का जवाब चाहिए कि जिस चिटफंड घोटाले ...,NOT,NONE,NONE,None
24,hasoc_hi_4057,नतीजे आने से पहले ज़िम्मेदारी मिलनी शुरू हो गय...,NOT,NONE,NONE,None
25,hasoc_hi_6455,क्लिक करें और पढ़ें इस स्मार्टफोन के बारे में..,NOT,NONE,NONE,None
26,hasoc_hi_1944,हद तो तब हो जाती हैं जब आरक्षण का लाभ लेने वा...,HOF,HATE,TIN,None
27,hasoc_hi_1796,#AIMIM National Spokesperson @syedasimwaqar li...,NOT,NONE,NONE,None
28,hasoc_hi_308,हरि ॐ नमो नारायणा भजन सुनकर झूम उठा भक्तों का ...,NOT,NONE,NONE,None
29,hasoc_hi_4604,प्लीज कॉल मेरी जबरदस्ती चुदाई करो ना,HOF,PRFN,UNT,None

Calculating HOF/NOT count

In [18]:
train_df[train_df["New_label"]=="HOF"]

,text_id,tweet,Original_label,task_2,task_3,New_label
11,hasoc_hi_288,गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...,NOT,NONE,NONE,HOF
99,hasoc_hi_495,मुस्लिम लोगों से वोट मांगने वाली पार्टियां क्य...,NOT,NONE,NONE,HOF
101,hasoc_hi_5808,बुर्का भी केवल लाचार मुस्लिम औरतों के लिए है। ...,NOT,NONE,NONE,HOF
271,hasoc_hi_767,अपने विष्लेसण की पुड़िया बना लो और इसको अपने *...,NOT,NONE,NONE,HOF
538,hasoc_hi_5778,चाट ते रहो चाट ते रहो चाट ते रहो चाट ते रहोच...,NOT,NONE,NONE,HOF
592,hasoc_hi_1975,शर्म करो डॉक्टरो एक थप्पड़ खाई और हड़ताल पर...,NOT,NONE,NONE,HOF
595,hasoc_hi_2285,"एक ही शब्द बना है इनके लिए #नीच, सोच से भी और ...",NOT,NONE,NONE,HOF
631,hasoc_hi_4401,बाई कडून पैसा घेणाऱ्याला शुद्ध मराठीत भडवा म्ह...,NOT,NONE,NONE,HOF
812,hasoc_hi_4620,क्या आपने कभी भारत के मुस्लिमो को पाकिस्तान का...,NOT,NONE,NONE,HOF
1062,hasoc_hi_844,"प्राकृतिक वर्फ भरे पहाड़, ठंड भरी ओस से गीली स...",NOT,NONE,NONE,HOF
1511,hasoc_hi_7582,मुसलमानों के नाम पर दिन रात आँसू बहाने वाली का...,NOT,NONE,NONE,HOF
1581,hasoc_hi_3997,जनता ने फैसला सुना दिया है। हमे #राष्ट्रवाद चा...,NOT,NONE,NONE,HOF
1837,hasoc_hi_3818,#देश का #मुस्लिम डरा हुआ है डर से #दिल्ली में ...,NOT,NONE,NONE,HOF
1849,hasoc_hi_5630,एक छोटी सी बच्ची गली में #कुत्तो को देखकर #डर ...,NOT,NONE,NONE,HOF
2084,hasoc_hi_6797,एका माणसाने दुसऱ्याला #नीच म्हटले तर त्यात चुक...,NOT,NONE,NONE,HOF
2342,hasoc_hi_4034,@RahulGandhi जी जितना मजाक उड़ाना है उड़ाइए......,NOT,NONE,NONE,HOF
2350,hasoc_hi_5360,"मीडिया लाॅबी का गाँड़ मारो, हिजड़े बच्चे जनते...",NOT,NONE,NONE,HOF
2383,hasoc_hi_7312,ये आपके नेता साहब के मुँह से रंड़ी हिजड़ा ये स...,NOT,NONE,NONE,HOF
2418,hasoc_hi_3400,दिल्ली में सारेआम एक मंदिर तोड दिया गया और ना ...,NOT,NONE,NONE,HOF
2479,hasoc_hi_3911,इस #डाॅक्टर को चाहिए था कि इसे एक ज़ोर का #थप...,NOT,NONE,NONE,HOF
2487,hasoc_hi_5830,@Uppolice https://youtu.be/hVq_kaP9N68 पंडित...,NOT,NONE,NONE,HOF
2494,hasoc_hi_134,कितना easy सवाल भारत क्या पूरे विश्व को पता है...,NOT,NONE,NONE,HOF
2556,hasoc_hi_5090,अय्यर के #नीच वाले बयान के लिए कांग्रेस जिम्मे...,NOT,NONE,NONE,HOF
2563,hasoc_hi_496,सकाळी गाणी टाकतो तो पोरींना पटवतो अन रात्री झो...,NOT,NONE,NONE,HOF
2569,hasoc_hi_2694,महबूबा रंडी और आतंकवादी उमर अब्दुल्ला को पाकिस...,NOT,NONE,NONE,HOF
2584,hasoc_hi_7138,रंडी मीडिया बोल रही कूटनीति थी हार । और जीत ज...,NOT,NONE,NONE,HOF
2599,hasoc_hi_709,भारत में सब से बड़े मास बीफ के व्यपारी हिन्दू ...,NOT,NONE,NONE,HOF
2633,hasoc_hi_2418,"भड़वा गैंग, उँगली यूजर मैडम, दलाल मीडिया,नाचने...",NOT,NONE,NONE,HOF
2640,hasoc_hi_7677,लीजिये मुजराबाजी शुरू हलाला वालीयों का चोर रं...,NOT,NONE,NONE,HOF
2645,hasoc_hi_4353,माणसाची सवय बदलता येते.पण जन्मजात निचपणा कसा स...,NOT,NONE,NONE,HOF
2660,hasoc_hi_4374,अंग्रेजों की गुलामी करने वाले और जय श्री राम ब...,NOT,NONE,NONE,HOF
2673,hasoc_hi_1179,@AbdullahAzamMLA साहब हम भी जानते है मदरसो से ...,NOT,NONE,NONE,HOF
2676,hasoc_hi_739,अब तो पाकिस्तान की हालत ऐसी हो गयी है कि अगर ...,NOT,NONE,NONE,HOF
2677,hasoc_hi_2339,अबु आझमी तर भड़वा आहे पण हे माझा वाले पन निर्ल...,NOT,NONE,NONE,HOF
2699,hasoc_hi_6979,लगता है #गांजे को लेकर आपका निशाना #राहुल_गाँध...,NOT,NONE,NONE,HOF
2762,hasoc_hi_3940,बेटा सामने मिलेगा तो नंगा कर के गांड पर हंटर म...,NOT,NONE,NONE,HOF
2794,hasoc_hi_5515,"फिर भी लिबरल, सेकुलर, बामपंथी, फेमिनिस्ट, भांड...",NOT,NONE,NONE,HOF
2814,hasoc_hi_2900,अभिनेत्री जायरा ने 'इस्लाम में अभिनय हराम' बता...,NOT,NONE,NONE,HOF
3225,hasoc_hi_1897,#ममताजी:- खा ले #कमीने लोग तू सब बिना खाये मुझ...,NOT,NONE,NONE,HOF
3227,hasoc_hi_3882,जो औरत आतंकवादियों की मौत पर बंद कमरे मे र...,NOT,NONE,NONE,HOF
3277,hasoc_hi_2889,गवारपने की हद से बाहर दिखता है ये जादू इस सुअ...,NOT,NONE,NONE,HOF
3339,hasoc_hi_752,"अगर 'इस्लाम' मे, फिल्मों मे एक्टिंग करना 'हराम...",NOT,NONE,NONE,HOF
3410,hasoc_hi_7126,जायरा वसीम ने कहा.. 'इस्लाम में अभिनय हराम'...,NOT,NONE,NONE,HOF
3435,hasoc_hi_4300,"सांप तो अपना काम पूरी ईमानदारी से करता है, काट...",NOT,NONE,NONE,HOF
3460,hasoc_hi_7456,"चोर मुल्ले को भीड़ मारे तो आसमान टूट पड़ता है,...",NOT,NONE,NONE,HOF
3503,hasoc_hi_2609,बाॅलिवुड के हिरो/हिरोईन ओर डायरेक्टर को दिखाओ ...,NOT,NONE,NONE,HOF
3607,hasoc_hi_2566,आप सब देशवासियों को ईद मुबारक आपका अपना #मोडी़...,NOT,NONE,NONE,HOF
3616,hasoc_hi_3679,तेरी परेशानी क्या है सुअर के पिल्ले मतलब दंगा...,NOT,NONE,NONE,HOF
3656,hasoc_hi_1011,भडवा गर्दी के पैसों से ख़रीदी है क्या कार,NOT,NONE,NONE,HOF
3788,hasoc_hi_1579,"मोदी ने जो #साजिश रची वह चौाकाने वाली नहीं, क्...",NOT,NONE,NONE,HOF
3806,hasoc_hi_5751,देशभक्त मोहम्मद शमी ने तीसरे मैच में भी 5 लिया...,NOT,NONE,NONE,HOF
4191,hasoc_hi_865,"Shamefull for Modi ji BJP, who is using ARMY, ...",NOT,NONE,NONE,HOF
4367,hasoc_hi_3459,"कृपया, आप इस रंडी की औलाद महमूद को कहां से ले ...",NOT,NONE,NONE,HOF
4643,hasoc_hi_5677,#Trump 1 - Ye ..Modi hi hai kya .. ? 2 - Are...,NOT,NONE,NONE,HOF

In [19]:
train_df[train_df["New_label"]=="NOT"]

,text_id,tweet,Original_label,task_2,task_3,New_label
121,hasoc_hi_4608,एसे #नीच और #घटिया लोगो को #चौराहे पर सबके स...,HOF,OFFN,TIN,NOT
405,hasoc_hi_5113,किसी राष्ट्र के प्रधानमंत्री के लिए अपशब्दों ग...,HOF,HATE,TIN,NOT
469,hasoc_hi_7232,#PMModi ने 25 जून को संसद में कहा कि #WaterCri...,HOF,HATE,TIN,NOT
470,hasoc_hi_404,"#AIMIM Chief @asadowaisi says to the Chair, '...",HOF,HATE,TIN,NOT
472,hasoc_hi_664,हनीप्रीत बिना पापा #RamRahim को खेतो में रोटी ...,HOF,HATE,TIN,NOT
...,...,...,...,...,...,...
4625,hasoc_hi_102,#Bihar के लोकप्रिय मुख्यमंत्री आदरणीय श्री @Ni...,HOF,HATE,TIN,NOT
4641,hasoc_hi_338,नीति आयोग की रिपोर्ट सरकार को लज्जित करने वाली...,HOF,HATE,TIN,NOT
4644,hasoc_hi_7422,देश का तिरंगा नीचे । भगवा झंडा तिरंगे से ऊपर ...,HOF,HATE,TIN,NOT
4647,hasoc_hi_4117,तू हवा के रुख पर चाहतो के दीप जलाने कि जिद न क...,HOF,HATE,TIN,NOT
4653,hasoc_hi_7198,अल्लाह के हुक्म से बग़ावत करना सीधे अल्लाह से ...,HOF,OFFN,TIN,NOT

In [20]:
hof_not_count=train_df["New_label"].value_counts()

In [21]:
hof_not_count

New_label
NOT    271
HOF     54
Name: count, dtype: int64

Filling the empty value in New_label column

In [22]:
train_df["New_label"] = train_df["New_label"].fillna(train_df["Original_label"])
#The New_label column stores relabeled annotations from iteration 1. For tweets that were not relabeled in this iteration, the values from Original_label are copied into New_label. <br/>

In [23]:
train_df.head(30)

,text_id,tweet,Original_label,task_2,task_3,New_label
0,hasoc_hi_5556,"बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...",NOT,NONE,NONE,NOT
1,hasoc_hi_5648,सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...,HOF,PRFN,UNT,HOF
2,hasoc_hi_164,तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...,HOF,PRFN,TIN,HOF
3,hasoc_hi_3530,"बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...",NOT,NONE,NONE,NOT
4,hasoc_hi_5206,चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...,NOT,NONE,NONE,NOT
5,hasoc_hi_5121,मुंबई में बारिश से लोगों को काफी समस्या हो रही है,NOT,NONE,NONE,NOT
6,hasoc_hi_7142,Ahmed's dad:-- beta aaj teri mammy kyu nahi ba...,NOT,NONE,NONE,NOT
7,hasoc_hi_4321,"5 लाख मुसलमान उर्स में, अजमेर की दरगाह पर आते ...",NOT,NONE,NONE,NOT
8,hasoc_hi_4674,"Do mahashaktiyan mili hain, charo taraf khusi ...",NOT,NONE,NONE,NOT
9,hasoc_hi_1637,Chants of 'Jai Sri Ram' as Owaisi takes oath: ...,NOT,NONE,NONE,NOT
10,hasoc_hi_5771,नृत्य होगा..! संगीत होगा..! जीवन मे उत्सव हो...,NOT,NONE,NONE,NOT
11,hasoc_hi_288,गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...,NOT,NONE,NONE,HOF
12,hasoc_hi_1803,डॉ. मुखर्जी ने एक देश में दो विधान दो प्रधान औ...,NOT,NONE,NONE,NOT
13,hasoc_hi_5900,धार्मिक पदों पर बैठे कुछ लोग अपने को भगवान समझ...,NOT,NONE,NONE,NOT
14,hasoc_hi_5951,सिक्का मोहब्बत का उछाल रक्खा है ~ हाँ मगर खुद...,NOT,NONE,NONE,NOT
15,hasoc_hi_1723,कोन कहता है आँखो में प्यार नही होता। जो डूब...,NOT,NONE,NONE,NOT
16,hasoc_hi_1691,"वैसे शपथ के अंत में ' जय भारत,जय संविधान' बोलन...",NOT,NONE,NONE,NOT
17,hasoc_hi_2070,"एक लंबे अंतराल के बाद आपके बीच #MannKiBaat, जन...",NOT,NONE,NONE,NOT
18,hasoc_hi_6865,"#नीच'समानार्थी शब्द #मोदी' दिला तर चालेल की, ल...",HOF,OFFN,TIN,HOF
19,hasoc_hi_918,डॉक्टर की लिखी 7 दिन की दवा के बजाय 3 दिन की...,NOT,NONE,NONE,NOT
20,hasoc_hi_3763,इस मादरचोद को धुण्डके गांड मे गोली मरो @Uppolice,HOF,PRFN,UNT,HOF
21,hasoc_hi_3228,"भारतीय रेल का सोमवार से बदल जाएगा टाइम-टेबल, ई...",NOT,NONE,NONE,NOT
22,hasoc_hi_5898,You cry in front of ur god Of being deceived ...,HOF,PRFN,UNT,HOF
23,hasoc_hi_3192,बस एक सवाल का जवाब चाहिए कि जिस चिटफंड घोटाले ...,NOT,NONE,NONE,NOT
24,hasoc_hi_4057,नतीजे आने से पहले ज़िम्मेदारी मिलनी शुरू हो गय...,NOT,NONE,NONE,NOT
25,hasoc_hi_6455,क्लिक करें और पढ़ें इस स्मार्टफोन के बारे में..,NOT,NONE,NONE,NOT
26,hasoc_hi_1944,हद तो तब हो जाती हैं जब आरक्षण का लाभ लेने वा...,HOF,HATE,TIN,HOF
27,hasoc_hi_1796,#AIMIM National Spokesperson @syedasimwaqar li...,NOT,NONE,NONE,NOT
28,hasoc_hi_308,हरि ॐ नमो नारायणा भजन सुनकर झूम उठा भक्तों का ...,NOT,NONE,NONE,NOT
29,hasoc_hi_4604,प्लीज कॉल मेरी जबरदस्ती चुदाई करो ना,HOF,PRFN,UNT,HOF

Finding the Disagreement Tweets

In [24]:
train_df['Mismatch'] = (train_df['Original_label'] != train_df['New_label']).astype(int)

In [25]:
mismatch_count = (train_df["Mismatch"] == 1).sum()
print("Count of tweets with mismatch column having value 1 indicating difference in original and new label",mismatch_count)

Count of tweets with mismatch column having value 1 indicating difference in original and new label 325

In [26]:
train_df.head(20)

,text_id,tweet,Original_label,task_2,task_3,New_label,Mismatch
0,hasoc_hi_5556,"बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...",NOT,NONE,NONE,NOT,0
1,hasoc_hi_5648,सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...,HOF,PRFN,UNT,HOF,0
2,hasoc_hi_164,तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...,HOF,PRFN,TIN,HOF,0
3,hasoc_hi_3530,"बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...",NOT,NONE,NONE,NOT,0
4,hasoc_hi_5206,चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...,NOT,NONE,NONE,NOT,0
5,hasoc_hi_5121,मुंबई में बारिश से लोगों को काफी समस्या हो रही है,NOT,NONE,NONE,NOT,0
6,hasoc_hi_7142,Ahmed's dad:-- beta aaj teri mammy kyu nahi ba...,NOT,NONE,NONE,NOT,0
7,hasoc_hi_4321,"5 लाख मुसलमान उर्स में, अजमेर की दरगाह पर आते ...",NOT,NONE,NONE,NOT,0
8,hasoc_hi_4674,"Do mahashaktiyan mili hain, charo taraf khusi ...",NOT,NONE,NONE,NOT,0
9,hasoc_hi_1637,Chants of 'Jai Sri Ram' as Owaisi takes oath: ...,NOT,NONE,NONE,NOT,0
10,hasoc_hi_5771,नृत्य होगा..! संगीत होगा..! जीवन मे उत्सव हो...,NOT,NONE,NONE,NOT,0
11,hasoc_hi_288,गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...,NOT,NONE,NONE,HOF,1
12,hasoc_hi_1803,डॉ. मुखर्जी ने एक देश में दो विधान दो प्रधान औ...,NOT,NONE,NONE,NOT,0
13,hasoc_hi_5900,धार्मिक पदों पर बैठे कुछ लोग अपने को भगवान समझ...,NOT,NONE,NONE,NOT,0
14,hasoc_hi_5951,सिक्का मोहब्बत का उछाल रक्खा है ~ हाँ मगर खुद...,NOT,NONE,NONE,NOT,0
15,hasoc_hi_1723,कोन कहता है आँखो में प्यार नही होता। जो डूब...,NOT,NONE,NONE,NOT,0
16,hasoc_hi_1691,"वैसे शपथ के अंत में ' जय भारत,जय संविधान' बोलन...",NOT,NONE,NONE,NOT,0
17,hasoc_hi_2070,"एक लंबे अंतराल के बाद आपके बीच #MannKiBaat, जन...",NOT,NONE,NONE,NOT,0
18,hasoc_hi_6865,"#नीच'समानार्थी शब्द #मोदी' दिला तर चालेल की, ल...",HOF,OFFN,TIN,HOF,0
19,hasoc_hi_918,डॉक्टर की लिखी 7 दिन की दवा के बजाय 3 दिन की...,NOT,NONE,NONE,NOT,0

In [27]:
train_df.to_csv("dataset/Hindi_alltasks.csv",index=False)

In this code, <br/>
1 we join original hasoc dataset with annotations for all tasks (Task1, Task2, Task3) with relabelled dataset <br/>

2 Relabelled is only done for original Task1 <br/>

3 Find the disagreeging tweets between Task1 (Original_Label column) and Relabelled (New_Label column) to produce new column Mismatch